export const CLOUDINARY_UPLOAD_REQUEST = "CLOUDINARY_UPLOAD_REQUEST";
export const CLOUDINARY_UPLOAD_SUCCESS = "CLOUDINARY_UPLOAD_SUCCESS";
export const CLOUDINARY_UPLOAD_FAIL = "CLOUDINARY_UPLOAD_FAIL";
export const CLOUDINARY_UPLOAD_RESET = "CLOUDINARY_UPLOAD_RESET";
